=== Maulyanda/XMLPendidikan/logpendidikan.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT logpendidikan (kebutuhan)+>
<!ATTLIST logpendidikan
    xmlns CDATA #FIXED ''>

<!ELEMENT kebutuhan (kode,nama,kategori,keterangan,tujuan,wilayah)>
<!ATTLIST kebutuhan
    xmlns CDATA #FIXED ''>

<!ELEMENT kode (#PCDATA)>
<!ATTLIST kode
    xmlns CDATA #FIXED ''>

<!ELEMENT nama (#PCDATA)>
<!ATTLIST nama
    xmlns CDATA #FIXED ''>

<!ELEMENT kategori (#PCDATA)>
<!ATTLIST kategori
    xmlns CDATA #FIXED ''>

<!ELEMENT keterangan (#PCDATA)>
<!ATTLIST keterangan
    xmlns CDATA #FIXED ''>

<!ELEMENT tujuan (siswa,umur,ket)>
<!ATTLIST tujuan
    xmlns CDATA #FIXED ''>

<!ELEMENT wilayah (kab,kota,kodewil)>
<!ATTLIST wilayah
    xmlns CDATA #FIXED ''>

<!ELEMENT siswa (#PCDATA)>
<!ATTLIST siswa
    xmlns CDATA #FIXED ''>

<!ELEMENT umur (#PCDATA)>
<!ATTLIST umur
    xmlns CDATA #FIXED ''>

<!ELEMENT ket (#PCDATA)>
<!ATTLIST ket
    xmlns CDATA #FIXED ''>

<!ELEMENT kab (#PCDATA)>
<!ATTLIST kab
    xmlns CDATA #FIXED ''>

<!ELEMENT kota (#PCDATA)>
<!ATTLIST kota
    xmlns CDATA #FIXED ''>

<!ELEMENT kodewil (#PCDATA)>
<!ATTLIST kodewil
    xmlns CDATA #FIXED ''>

=== Maulyanda/XMLPendidikan/pendidikan.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE logpendidikan SYSTEM "logpendidikan.dtd">
<logpendidikan>
<kebutuhan>
	<kode>1</kode>
	<nama>Les Privat</nama>
	<kategori>Les</kategori>
	<keterangan>Les privat nampaknya menjadi bisnis di bidang pendidikan yang membutuhkan modal relatif kecil,
		namun bisa menjanjikan penghasilan yang relatif besar.</keterangan>
	<tujuan>
		<siswa>Siswa/Siswi</siswa>
		<umur>6 sampai 16 Tahun</umur>
		<ket>Membantu anak didik terutama anak SD yang merasa kesulitan mendalami pelajaran di sekolah</ket>
	</tujuan>
	<wilayah>
		<kab>Jawa Barat</kab>
		<kota>Bandung</kota>
		<kodewil>32</kodewil>
	</wilayah>
</kebutuhan>

<kebutuhan>
	<kode>2</kode>
	<nama>Les Baca Tulis Hitung</nama>
	<kategori>Les</kategori>
	<keterangan>Les Baca Tulis Hitung menjadi bisnis di bidang pendidikan Bisnis ini bisa Anda tekuni terutama Anda yang memang menyukai dan sabar terhadap anak-anak.</keterangan>
	<tujuan>
		<siswa>TK</siswa>
		<umur>5 Tahun</umur>
		<ket>Membantu anak yang merasa kesulitan membaca, menulis, dan menghitung</ket>
	</tujuan>
	<wilayah>
		<kab>Jawa Barat</kab>
		<kota>Bandung</kota>
		<kodewil>32</kodewil>
	</wilayah>
</kebutuhan>

<kebutuhan>
	<kode>3</kode>
	<nama>Pendidikan Anak Usia Dini</nama>
	<kategori>PAUD</kategori>
	<keterangan>PAUD merupakan singkatan dari Pendidikan Anak Usia Dini.</keterangan>
	<tujuan>
		<siswa>paud</siswa>
		<umur>4 Tahun</umur>
		<ket>Membantu anak usia dini dalam belajar</ket>
	</tujuan>
	<wilayah>
		<kab>Jawa Barat</kab>
		<kota>Bandung</kota>
		<kodewil>32</kodewil>
	</wilayah>
</kebutuhan>

<kebutuhan>
	<kode>4</kode>
	<nama>Kursus Bahasa Asing</nama>
	<kategori>Kursus</kategori>
	<keterangan>kemampuan bahasa asing menjadi salah satu keterampilan yang wajib dimiliki untuk melamar pekerjaan, setidaknya kemampuan untuk berbahasa Inggris.</keterangan>
	<tujuan>
		<siswa>Siswa Dan Mahasiswa</siswa>
		<umur>6 sampai 20 Tahun</umur>
		<ket>Membantu dalam meningkatkan bahasa asing terutama bahasa inggris.</ket>
	</tujuan>
	<wilayah>
		<kab>Jawa Barat</kab>
		<kota>Bandung</kota>
		<kodewil>32</kodewil>
	</wilayah>
</kebutuhan>

<kebutuhan>
	<kode>5</kode>
	<nama>Kursus Komputer</nama>
	<kategori>Kursus</kategori>
	<keterangan>Selain mampu berkomunikasi dalam bahasa asing, kemampuan dan keterampilan lain yang tidak kalah penting untuk melamar pekerjaan dalam sebuah perusahaan adalah keterampilan menggunakan komputer beserta software di dalamnya.</keterangan>
	<tujuan>
		<siswa>Siswa Dan Mahasiswa</siswa>
		<umur>14 sampai 23 Tahun</umur>
		<ket>Membantu dalam meningkatkan dalam menggunakan komputer yang dibutuhkan perusahaan</ket>
	</tujuan>
	<wilayah>
		<kab> Jawa Barat</kab>
		<kota>Bandung</kota>
		<kodewil>32</kodewil>
	</wilayah>
</kebutuhan>

</logpendidikan>
